apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      pod: products
      version: '1'
  template:
    metadata:
      labels:
        pod: products
        version: '1'
    spec:
      serviceAccountName: products
      initContainers:
        - name: wait-for-products-db-migrate-job
          image: groundnuty/k8s-wait-for:v2.0
          args:
            - job
            - products-db-migrate
      containers:
        - name: products
          image: products-image-placeholder
          resources:
            limits:
              memory: 500Mi
              cpu: '0.2'
          ports:
            - containerPort: 3000
              name: default
          envFrom:
            - configMapRef:
                name: products-db-config
            - secretRef:
                name: products-db-credentials

          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 3000
          #   initialDelaySeconds: 2
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 3000
          #   initialDelaySeconds: 2
          #   periodSeconds: 5
