apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: products-db-claim
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
