apiVersion: v1
kind: PersistentVolume
metadata:
  name: products-db-volume
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/ms-demo/products-db
    type: DirectoryOrCreate
