apiVersion: v1
kind: ServiceAccount
metadata:
  name: products
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: products
rules:
  - apiGroups: ['']
    resources: ['pods', 'services']
    verbs: ['get', 'watch', 'list']
  - apiGroups: ['batch']
    resources: ['jobs']
    verbs: ['get', 'watch', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: products
subjects:
  - kind: ServiceAccount
    name: products
roleRef:
  kind: Role
  name: products
  apiGroup: rbac.authorization.k8s.io
