apiVersion: skaffold/v3
kind: Config
manifests:
  kustomize:
    paths:
      - ./deploy/k8s/overlays/local/.
build:
  local:
    push: false
  artifacts:
    - image: msgxxx/ms-demo-auth
      context: ./apps/auth/.
      docker:
        dockerfile: Dockerfile.local
      sync:
        infer:
          - src/**/*.*

    - image: msgxxx/ms-demo-products
      context: ./apps/products/.
      docker:
        dockerfile: Dockerfile.local
      sync:
        infer:
          - src/**/*.*
portForward:
  - resourceType: service
    resourceName: auth
    port: 80
    localPort: 5000

  - resourceType: service
    resourceName: auth-db-h
    port: 27017
    localPort: 27017

  - resourceType: service
    resourceName: products
    port: 80
    localPort: 5001

  - resourceType: service
    resourceName: products-db-h
    port: 5432
    localPort: 5432
