# Unfortunately we cannot use node:alpine with mongodb in-memory server - https://nodkz.github.io/mongodb-memory-server/docs/guides/known-issues/#no-build-available-for-alpine-linux
# So this image exists purely to be able to run e2e tests in CI pipeline
FROM node:18

COPY package*.json ./

RUN npm ci

COPY . ./

RUN npm run test:e2e
