FROM node:18-alpine

RUN mkdir app && chown node app

WORKDIR /app

COPY --chown=node:node package*.json ./

RUN npm ci

COPY --chown=node:node . ./

# run unit tests
RUN npm run test

USER node

CMD [ "npm", "run", "start:dev" ]