apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
spec:
  selector:
    matchLabels:
      app: auth-db
      version: '1'
  serviceName: auth-db-h
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-db
        version: '1'
    spec:
      containers:
        - name: auth-db
          image: mongo:6.0.2
          ports:
            - containerPort: 27017
              name: default
          volumeMounts:
            - name: data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-db-credentials
                  key: MONGODB_USER
                  optional: false
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db-credentials
                  key: MONGODB_PASSWORD
                  optional: false
          readinessProbe:
            exec:
              command: ['mongosh', '--eval', 'db.adminCommand({ ping: 1 })']
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: auth-db-claim
