apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-db-volume
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /tmp/data/auth-db
    type: DirectoryOrCreate
  # local:
  #   path: /Volumes/ms-demo/auth-db
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: kubernetes.io/hostname
  #             operator: In
  #             values:
  #               - docker-desktop
