apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      pod: auth
      version: '1'
  template:
    metadata:
      labels:
        pod: auth
        version: '1'
    spec:
      containers:
        - name: auth
          image: auth-image
          resources:
            limits:
              memory: 1Gi
              cpu: 1
          ports:
            - containerPort: 3000
              name: default
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: auth-db-credentials
                  key: MONGODB_USER
                  optional: false
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db-credentials
                  key: MONGODB_PASSWORD
                  optional: false
          envFrom:
            - configMapRef:
                name: auth-db-config
            - secretRef:
                name: jwt-secret
  strategy:
    type: Recreate
