apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: auth
commonAnnotations:
  owner: mikkel
  email: bla@bla.com
resources:
  - auth-db.volume.yaml
  - auth-db.claim.yaml
  - auth-db.service.yaml
  - auth-db.statefulset.yaml
  - auth.service.yaml
  - auth.deployment.yaml
