apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
  namespace: demo
spec:
  selector:
    matchLabels:
      app: auth-db
  serviceName: auth-db-service-h
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: auth-db
          image: mongo:6.0.2
          ports:
            - containerPort: 27017
              name: default
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          emptyDir: {}
