apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-db-volume
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/ms-demo/auth-db
