apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ms-demo-prod
nameSuffix: -prod
commonLabels:
  env: prod
bases:
  - ../../base
secretGenerator:
  - name: auth-db-credentials
    envs:
      - .env.auth-db-credentials
  - name: jwt-secret
    envs:
      - .env.jwt-secret
