apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ms-demo-prod
nameSuffix: -prod
commonLabels:
  env: prod
secretGenerator:
- envs:
  - .env.auth-db-credentials
  name: auth-db-credentials
- envs:
  - .env.jwt-secret
  name: jwt-secret
resources:
- ../../base
images:
- name: auth-image
  newName: msgxxx/ms-demo-auth
  newTag: branch-master-c96d81b6
