apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ms-demo-prod
commonLabels:
  env: prod
configMapGenerator:
- envs:
  - .env.auth-db-config
  name: auth-db-config
- envs:
  - .env.products-db-config
  name: products-db-config
secretGenerator:
- envs:
  - .env.auth-db-credentials
  name: auth-db-credentials
- envs:
  - .env.jwt-secret
  name: jwt-secret
resources:
- ../../base
images:
- name: auth-image-placeholder
  newName: msgxxx/ms-demo-auth
  newTag: branch-master-fd8f9504
- name: products-image-placeholder
  newName: msgxxx/ms-demo-products
  newTag: branch-master-0a9d6f39
