name: Build and push a image to Docker hub

on:
  workflow_call:
    inputs:
      image_repo:
        required: true
        type: string
      docker_context:
        required: true
        type: string
      push_to_registry:
        required: true
        type: boolean
      docker_hub_username:
        required: true
        type: string

    secrets:
      DOCKER_HUB_ACCESS_TOKEN:
        required: false

    outputs:
      image_tag:
        description: 'The nag of the newly built image'
        value: ${{ jobs.build-push.outputs.image_tag }}
        
jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.create-tag.outputs.image_tag }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{ inputs.push_to_registry }}
        with:
          username: ${{ inputs.docker_hub_username }}
          password: ${{ secrets.docker_hub_access_token }}
          
      - name: Set Github "short sha" as env variable
        run: echo "github_short_sha=$(echo ${{ github.sha }} | cut -c 1-8)" >> $GITHUB_ENV
          
      - name: Create image tag
        id: create-tag
        run: echo "image_tag=${{ inputs.docker_hub_username }}/${{ inputs.image_repo }}:${{ github.ref_type }}-${{ github.ref_name }}-${{ env.github_short_sha }}"  >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.docker_context }}
          push: ${{ inputs.push_to_registry }}
          tags: ${{ steps.create-tag.outputs.image_tag }}

      
