name: Build and deploy Auth service

on:
  workflow_dispatch

  # push:
  #   branches: [ "master" ]
  #   paths:
  #     - apps/auth/**

jobs:
  test:
    uses: ./.github/workflows/test-auth-service.yml

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Docker meta data
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            msgxxx/ms-demo-auth

          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./apps/auth
          file: ./apps/auth/Dockerfile.dev
          push: true
          tags: ${{ steps.meta.outputs.tags }}
