name: Build and deploy Auth service

on:
  workflow_dispatch
  
 # push:
 #   branches: [ "master" ]
 #   paths:
 #     - apps/auth/**    
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout source code
      uses: actions/checkout@v3
      
      
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    -
      name: Build docker image
      run: docker build ./apps/auth -f ./apps/auth/Dockerfile.dev -t msgxxx/ms-demo-auth:${{ github.sha }}
    
    
    -
      name: Push docker image
      run: docker push msgxxx/ms-demo-auth:${{ GITHUB_SHA }}
