name: Test auth service

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Run unit tests & e2e tests
        uses: docker/build-push-action@v3
        with:
          context: ./apps/auth
          file: ./apps/auth/Dockerfile.test
