apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ms-demo-dev
commonLabels:
  env: dev
bases:
  - ../../base
configMapGenerator:
  - name: auth-db-config
    envs:
      - .env.auth-db-config
  - name: products-db-config
    envs:
      - .env.products-db-config
secretGenerator:
  - name: auth-db-credentials
    envs:
      - .env.auth-db-credentials

  - name: products-db-credentials
    envs:
      - .env.products-db-credentials

  - name: jwt-secret
    envs:
      - .env.jwt-secret
